#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

containerName=PoMa-client
isRunning="$(docker ps -q -f name=$containerName)"

if [ -z "$isRunning" ]
then
  echo "\n\033[31mPlease start docker container ($containerName) so test can run !\033[0m\n"
  exit 1
fi

npx lint-staged  --verbose
docker exec PoMa-client yarn test
